export const TRANSACTION_TYPE = {

};

export const TRANSACTION_DIRECTION = {

};

export const ACCOUNT_STATE_CHANGE_ACTION = {

};

export const METADATA_KEYS = {
	ACCOUNT_NAME: 'fnet_account_name',
	ACCOUNT_BIO: 'fnet_account_bio'
}

export const SENDING_OPTIONS = {
	TRANSACTION_URI: 'TRANSACTION_URI',
	PRINT_PAYLOAD: 'PRINT_PAYLOAD',
	PRINT_FIELDS: 'PRINT_FIELDS',
	SSS: 'SSS',
}

export const STORAGE_KEY = {
	USER_ADDRESS: 'USER_ADDRESS',
	SENDING_OPTION: 'SENDING_OPTION',
	BOOKMARKS_AUTHORS: 'BOOKMARKS_AUTHORS',
	TIMESTAMP_TYPE: 'TIMESTAMP_TYPE',
	USER_LANGUAGE: 'USER_LANGUAGE',
	USER_CURRENCY: 'USER_CURRENCY'
};

export const SUPPLY_CHANGE_ACTION = {

};

export const COSIGNATORY_MODIFICATION_ACTION = {

};

export const KEY_LINK_ACTION = {

};

export const MESSAGE_TYPES = {
    POST: 1,
    COMMENT: 2,
    LIKE: 3,
	ACCOUNT_NAME: 4,
	ACCOUNT_ACTIVATION: 5,
	DONATE: 6
}

export const MAX_VALUE_SIZE = 900;
