const config = {
	NETWORK_TYPE: process.env.NEXT_PUBLIC_NETWORK_TYPE,
	NATIVE_MOSAIC_ID: process.env.NEXT_PUBLIC_NATIVE_MOSAIC_ID,
	NATIVE_MOSAIC_TICKER: process.env.NEXT_PUBLIC_NATIVE_MOSAIC_TICKER,
	NATIVE_MOSAIC_DIVISIBILITY: +process.env.NEXT_PUBLIC_NATIVE_MOSAIC_DIVISIBILITY,
	EPOCH_ADJUSTMENT: +process.env.NEXT_PUBLIC_EPOCH_ADJUSTMENT,
	REQUEST_TIMEOUT: +process.env.NEXT_PUBLIC_REQUEST_TIMEOUT,
	NODELIST_URL: process.env.NEXT_PUBLIC_NODELIST_URL,
	DEFAULT_NODES: process.env.NEXT_PUBLIC_DEFAULT_NODES ? process.env.NEXT_PUBLIC_DEFAULT_NODES.split(',') : [],
	SYMBOL_WALLET_ANDROID_URL: process.env.NEXT_PUBLIC_SYMBOL_WALLET_ANDROID_URL,
	SYMBOL_WALLET_IOS_URL: process.env.NEXT_PUBLIC_SYMBOL_WALLET_IOS_URL,
	SSS_WALLET_CHROME_URL: process.env.NEXT_PUBLIC_SSS_WALLET_CHROME_URL,
	SYMBOL_WALLET_CHROME_URL: process.env.NEXT_PUBLIC_SYMBOL_WALLET_CHROME_URL,
};

export default config;
